"""
Report generation module for AgenticAI
Handles saving results to JSON and HTML formats
"""

import json
from datetime import datetime


def save_to_json(data, filename="research_results.json"):
    """
    Save research results to JSON file
    
    Args:
        data (dict): Research data to save
        filename (str): Output JSON filename
    """
    with open(filename, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"JSON saved: {filename}")


def save_to_html(data, filename="research_results.html"):
    """
    Save research results to HTML file with styling
    
    Args:
        data (dict): Research data to save
        filename (str): Output HTML filename
    """
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgenticAI - Research Results</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }}
        
        .container {{
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }}
        
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        
        .header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        
        .header p {{
            font-size: 1.1em;
            opacity: 0.9;
        }}
        
        .metadata {{
            background: #f5f5f5;
            padding: 20px;
            border-bottom: 1px solid #ddd;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }}
        
        .metadata-item {{
            display: flex;
            align-items: center;
        }}
        
        .metadata-label {{
            font-weight: bold;
            color: #667eea;
            margin-right: 10px;
        }}
        
        .content {{
            padding: 40px;
        }}
        
        .response {{
            line-height: 1.8;
            color: #333;
            white-space: pre-wrap;
            word-wrap: break-word;
            background: #f9f9f9;
            padding: 20px;
            border-radius: 5px;
            border-left: 4px solid #667eea;
        }}
        
        .footer {{
            background: #f5f5f5;
            padding: 20px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
            border-top: 1px solid #ddd;
        }}
        
        @media (max-width: 600px) {{
            .metadata {{
                grid-template-columns: 1fr;
            }}
            
            .header h1 {{
                font-size: 1.8em;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AgenticAI</h1>
            <p>Tech Researcher Agent - Research Results</p>
        </div>
        
        <div class="metadata">
            <div class="metadata-item">
                <span class="metadata-label">Task:</span>
                <span>{data['task']}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Model:</span>
                <span>{data['model']}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Generated:</span>
                <span>{data['timestamp']}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Status:</span>
                <span style="color: green; font-weight: bold;">Success</span>
            </div>
        </div>
        
        <div class="content">
            <h2 style="margin-bottom: 20px; color: #667eea;">Research Results</h2>
            <div class="response">{data['response']}</div>
        </div>
        
        <div class="footer">
            <p>Generated by AgenticAI | Local LLM using Ollama</p>
        </div>
    </div>
</body>
</html>"""
    
    with open(filename, 'w') as f:
        f.write(html_content)
    print(f"HTML saved: {filename}")


def generate_report(response_text, task, model):
    """
    Generate and save both JSON and HTML reports
    
    Args:
        response_text (str): The AI response text
        task (str): Description of the task
        model (str): Name of the model used
    """
    data = {
        "task": task,
        "model": model,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "response": response_text,
        "status": "success"
    }
    
    save_to_json(data)
    save_to_html(data)
    
    return data
